CREATE TABLE client (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL CHECK (LENGTH(name) >= 3),
  cpf CHAR(11) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE address (
  id SERIAL PRIMARY KEY,
  client_id INTEGER REFERENCES client(id),
  cep CHAR(8) NOT NULL,
  street_address TEXT NOT NULL,
  neighborhood TEXT NOT NULL,
  city TEXT NOT NULL,
  state CHAR(2) NOT NULL,
  complement TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE phone (
  id SERIAL PRIMARY KEY,
  client_id INTEGER REFERENCES client(id),
  number CHAR(11) NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email (
  id SERIAL PRIMARY KEY,
  client_id INTEGER REFERENCES client(id),
  email_address TEXT NOT NULL CHECK (POSITION('@' IN email_address) > 1),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
